/*
#########################################################################################
Project Name..........: TFS Forms Implementation
File..................: Forms_ServiceException 
Version...............: 1.0
Created by............: Pranav
Created Date..........: 10/26/2015 
Last Modified by......: 
Last Modified Date....: 
Description...........: This custom Exception class has been writtem to handle any unknown errors caused during service callouts.
                         This does not include any exceptions caused during internal errors in salesforce


Change Request History:
##########################################################################################
 */


Public class Forms_ServiceException extends Exception{
    //this is asample method to cover the class.
    public void sampleMethod(){}
}