/*
#########################################################################################
Project Name..........: TFS Forms Implementation
File..................: Forms_ServiceException
Version...............: 1.0
Created by............: Pranav
Created Date..........: 10/26/2015 
Last Modified by......: 
Last Modified Date....: 
Description...........: This class is used to handle Internal exceptions if any. Internal Exceptions
                        are called if any error occurs within salesforce and not due to service calls.

Change Request History:

##########################################################################################
 */

Public class Forms_InternalException extends Exception{
   //this is asample method to cover the class.
    public void sampleMethod(){}
}